name: Python with PostgreSQL

on:
  push:
    branches:
      - main

jobs:
  test-python-with-postgres:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432

    
    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Ensure PostgreSQL is ready
    - name: Wait for PostgreSQL to be ready
      run: |
        for i in {1..30}; do
          if pg_isready -h localhost -p 5432 -U user; then
            echo "PostgreSQL is ready!"
            break
          fi
          echo "Waiting for PostgreSQL..."
          sleep 1
        done

    # Run the first Python script
    - name: Run first Python script
      run: python main.py
      env:
        DATABASE_URL: postgres://user:password@localhost:5432/test_db
